### ISSUE TITLE
Missing dependencies in pip v0.0.7

### ISSUE THREAD

**Issue by generein** [LyceanEM/LyceanEM-Python#12]
I installed v0.07 in a fresh python 3.9 conda environment (with spyder, numpy, matplotlib). When trying to run (new) example [05_array_beamforming.py](https://github.com/LyceanEM/LyceanEM-Python/blob/master/docs/examples/05_array_beamforming.py), it throws up missing packages: meshio and pygmsh. Once installed, the example runs fine, but they are missing dependencies in the pip installation.

**Comment by LyceanEM** [comment]
Thank you for raising this issue, the required packages have now been added to the pip requirements.
